### ISSUE TITLE
Minimum Dwell Time

### ISSUE THREAD

**Issue by allanjuma** [w3c/geofencing-api#14]
might it be a good idea to set a minimum dwell time variable to a geofence? This would indicate how long the event should wait before firing the on-enter event incase the user is just "passing-by" the geofence area..?

**Comment by mkruisselbrink** [comment]
I'm not sure, I think I'd rather leave it up to the user agent (with presumably better knowledge of the hardware) to determine what it considers a geofence being entered/left. Also something like androids "dwell" transition could be implemented on top of the enter/leave events (but admittedly somewhat complicated by the fact that service workers can get killed fairly often).

**Comment by allanjuma** [comment]
Makes sense. So how can we test it out and give more feedback?

**Comment by mkruisselbrink** [comment]
Currently no browser implement this spec yet. I'm working on the Chrome implementation, but I'm not sure yet when that will be in a state where this can be tested.
