### ISSUE TITLE
Editorial Issues re: June 22 2015 Draft (from Josh Soref)

### ISSUE THREAD

**Issue by gmandyam** [w3c/geofencing-api#17]
> The Geofencing API lets webapps setup geographic boundaries around

set up

> Example 4: Unmonitor a region in response to some other event

"Unmonitor" isn't a word, please use "Stop monitoring"

> A geofence is a tuple consisting of a geographic region, geofence ID and a [sic] include position flag.

an

> Ask the user whether they allow the webapp to use geofences, unless a prearranged trust relationship applies or the user has already granted or denied permission explicitly for this webapp.

granted or denied permission _for_what_? did you forget to mention "for this api"?

> Resolve promise with a new Geofence instance representing the geofence.

normally one would `construct` a Geofence, initialize its fields, and then resolve something with it....

> If the geofences includePosition attribute is true, set event.position to the current geographical position.

geofence's

> The user agent MAY wait with firing a geofence event until some time 
> has passed after the breach was detected

with firing => delay firing | until firing | to fire

> Let event be a new GeofenceErrorEvent, whose geofence attribute is a new Geofence instance representing the geofence for which an error was detected.

The UA didn't detect an error, it detected a problem ("situation") and is generating an error.

**Comment by mkruisselbrink** [comment]
I think I addressed all these, other than:

> > Resolve promise with a new Geofence instance representing the geofence.
> 
> normally one would construct a Geofence, initialize its fields, and then resolve something with it....

I think the current text better explains what is going on. The fields of the new `Geofence` aren't some static copy of the geofence at the time it is instantiated, they return whatever the current value is of the geofence that is represented by the `Geofence` instance. Also pretty much the exact same language is used all over the service worker spec whenever a `ServiceWorker` or `ServiceWorkerRegistration` is returned.
