### ISSUE TITLE
getbyID() method:  Resolving promise with null when ID not found (from Josh Soref)

### ISSUE THREAD

**Issue by gmandyam** [w3c/geofencing-api#20]
Sec. 6.2

> If promise was not resolved, resolve promise with null.

why not reject with notfound?

**Comment by mkruisselbrink** [comment]
Because rejecting a promise should be done where a non-promise using API would throw an exception. Not finding a geofence is not such a situation (similarly getElementByID, navigator.serviceWorker.getRegistration("..."), etc all also return/resolve with null when not found).
