### ISSUE TITLE
CircularGeofenceRegion radius should be radius_m

### ISSUE THREAD

**Issue by garvankeeley** [w3c/geofencing-api#24]
What unit is radius in CircularGeofenceRegion? It appears to be meters, but I didn't see that documented.
Perhaps make it self documenting and use the SI unit short form as a suffix on the name? 

http://www.ewh.ieee.org/soc/ias/pub-dept/abbreviation.pdf

**Comment by mkruisselbrink** [comment]
I don't really like adding the unit as suffix on the name, but it should of course be documented what unit this is in. Not sure how that got lost.
