### ISSUE TITLE
Redudant assertion

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/geofencing-api#3]
This is redundant: 

> "The geofencing attribute exposes a GeofenceManager, which has an associated service worker registration represented by the ServiceWorkerRegistration on which the attribute is exposed."

As the IDL already says that, you don't need the above.

**Comment by mkruisselbrink** [comment]
I'm not sure about this. I kind of agree that the text doesn't add much, but it also seems weird to have a field without any description.

At least the push-api spec has similar language: "[The pushManager attribute exposes a PushManager, which has an associated service worker registration represented by the ServiceWorkerRegistration on which the attribute is exposed](https://w3c.github.io/push-api/#widl-ServiceWorkerRegistration-pushManager) (and phrased slightly different in the [WD](http://www.w3.org/TR/push-api/#widl-ServiceWorkerRegistration-pushRegistrationManager)).

**Comment by marcoscaceres** [comment]
> I'm not sure about this. I kind of agree that the text doesn't add much, but it also seems weird to have a field without any description.

Only add a description if it needs a description. Seriously tho, here you don't need one. It means you need to keep two things up to date. 

> At least the push-api spec..

Not known to be the best example of a well-written spec. Example of a good spec: https://fetch.spec.whatwg.org

**Comment by mkruisselbrink** [comment]
That makes sense. Somehow I always make the mistakes of copying from the wrong examples :)
