### ISSUE TITLE
Move uniqueness of id

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/geofencing-api#5]
The spec says:

> This ID MUST be unique across all geofences for this particular origin. 

This should be moved to the definition of a geofence ID as a statement of fact.

**Comment by marcoscaceres** [comment]
There is also: 

>  This ID is generated by the user agent and MUST be unique among all current geofences for the same origin, but can be the same as an ID for a geofence at a different origin. This ID MUST NOT change as long as this geofence exists. The generated ID SHOULD NOT be the same as an ID for any geofence that existed before at the same origin. 

All this should be in one place.

**Comment by marcoscaceres** [comment]
(i.e., where where geofence id is formally defined)

**Comment by mkruisselbrink** [comment]
I agree that having this duplicated is not good. I'm not entirely sure what an appropriate place to define this would be though. I've now moved it to the terminology section, but maybe that's not entirely the right place.
