### ISSUE TITLE
What is a sequence?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/geofencing-api#6]
The spec says:

> Let geofences be a new sequence. 

This should be either an array or a set... it's not clear what a "sequence" binds to in JS.

**Comment by mkruisselbrink** [comment]
So it's not enough that webidl defines a sequence and that it binds to an array in JS? I'll change it to array...

**Comment by marcoscaceres** [comment]
No, sorry! I had totally forgotten about sequence. Can you please link to WebIDL sequence.
