### ISSUE TITLE
Simplifying examples even further

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/geofencing-api#9]
Would you object to me rewriting the examples to use ES7 `async function(){}` and argument destructuring? Could probably make the examples a bit nicer to read.

**Comment by mkruisselbrink** [comment]
I think it's better to keep the examples conforming to ES6 until there is actual consensus on ES7 and ES7 is actually a standard.

**Comment by marcoscaceres** [comment]
yeah, fair enough :)
